services:
  iqdb:
    image: evazion/iqdb
    container_name: iqdb.yiff-rocks
    command: ["http", "0.0.0.0", "5588", "/data/iqdb.db"]
    volumes:
      - iqdb_data:/data
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :5588 || exit 1
    networks:
      default:
        ipv4_address: 172.19.3.3 

  redis:
    image: redis:alpine
    container_name: redis.yiff-rocks
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    networks:
      default:
        ipv4_address: 172.19.3.4

  mariadb:
    image: mariadb
    container_name: mariadb.yiff-rocks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    healthcheck:
      interval: 5s
      timeout: 2s
      test: mysqladmin ping
    networks:
      default:
        ipv4_address: 172.19.3.5

networks:
  default:
    name: yiff-rocks
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/24
          gateway: 172.19.3.1

volumes:
  iqdb_data:
  redis_data:
  db_data:
