CREATE TABLE `posts` (
	`id`              INT UNSIGNED                                           NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`uploader`        INT UNSIGNED                                           NOT NULL,
	`approver`        INT UNSIGNED                                           NULL,
	`created_at`      TIMESTAMP(3)                                           NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`updated_at`      TIMESTAMP(3)                                           NULL,
	`version`         INT UNSIGNED                                           NOT NULL,
	`versions`        TEXT                                                   NOT NULL,
	`revision`        INT UNSIGNED                                           NOT NULL DEFAULT 0,
	`score_up`        INT UNSIGNED                                           NOT NULL DEFAULT 0,
	`score_down`      INT UNSIGNED                                           NOT NULL DEFAULT 0,
	`sources`         TEXT                                                   NOT NULL DEFAULT '',
	`favorite_count`  INT UNSIGNED                                           NOT NULL DEFAULT 0,
	`tags`            MEDIUMTEXT                                             NOT NULL DEFAULT '',
	`locked_tags`     MEDIUMTEXT                                             NOT NULL DEFAULT '',
	-- 1 (PENDING)
	`flags`           INT UNSIGNED                                           NOT NULL DEFAULT 1,
	`rating`          ENUM('safe', 'questionable', 'explicit')               NOT NULL DEFAULT 'explicit',
	`rating_lock`     ENUM('minimum', 'exact', 'maximum')                    NULL,
	`files`           TEXT                                                   NOT NULL DEFAULT '',
	`parent`          INT UNSIGNED                                           NULL,
	`childeren`       TEXT                                                   NULL,
	`pools`           TEXT                                                   NULL,
	`description`     TEXT                                                   NOT NULL DEFAULT '',
	`title`           TEXT                                                   NOT NULL DEFAULT '',
	`comment_count`   INT UNSIGNED                                           NOT NULL DEFAULT 0,
	`duration`        INT UNSIGNED                                           NULL,
	`type`            ENUM('png', 'apng', 'jpg', 'gif', 'video', 'unknown')  NOT NULL DEFAULT 'unknown',

	-- Indexes
	UNIQUE INDEX  `id`           (`id`),
	UNIQUE INDEX  `id_revision`  (`id`, `revision`),
	INDEX         `uploader`     (`uploader`),
	INDEX         `approver`     (`approver`),
	INDEX         `version`      (`version`),
	INDEX         `flags`        (`flags`),
	INDEX         `rating`       (`rating`),
	INDEX         `rating_lock`  (`rating_lock`),
	INDEX         `parent`       (`parent`),
	INDEX         `type`         (`type`)
)
